<?php
$title = 'Get information about cable';
//$this->headTitle($title);
//$this->headMeta()->setCharset('UTF-8');
?>
<h1><? echo $this->escapeHtml($title);?></h1>
<?
$form = $this->form;
$form->setAttribute('action', $this->url('barcervice', array('action' => 'index')));
$form->prepare();

if ($this->messages)
	foreach ($this->messages as $key => $message)
	{echo '<div>'.$key.' - ';
	var_dump($message); echo '</div>';}
$CabFieldset = $form->getElements();
echo $this->form()->openTag($form);
echo '<table class="form-cable-display"><tbody>';
foreach ($CabFieldset as $key => $value)
	{
		echo 
		'<tr><td>'.$value->getLabel().'</td>
		 <td>'.$this->formElement($value).'</td></tr>';
	}
echo '</tbody></table>';
echo $this->form()->closeTag();

//Вывод результатов рассчета
if (!empty($this->dimensions)){
	echo '<hr>';
	if (($form->get('byAllBarTypes')->getValue()) == 'Yes')
		// Если включен множественный выбор типа барабана
		//строим таблицу результатов
		{
			echo '<table class="form-cable-display"><tbody><tr>';
			foreach ($this->dimensions as $key => $value)
				echo '<td><th>'.$key.'</th></td>';
			echo '</tr></tbody></table>';
		}
		else{
			echo '<div>Parameters of cable</div>';
			foreach ($this->dimensions as $key => $value)
				echo '<div>'.$key.' = '.$value.'</div>';				
		}
	echo '<hr>';
}
